baseURL = "https://cu.shoogle.net/cuba/"
languageCode = "es"
title = "Cuba"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "cuba"

[taxonomies]
  shop = "shops"

